export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_FULFILLED = 'ADD_TO_CART_FULFILLED';
export const ADD_TO_CART_REJECTED = 'ADD_TO_CART_REJECTED';

export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_CART_PENDING = 'UPDATE_CART_PENDING';
export const UPDATE_CART_FULFILLED = 'UPDATE_CART_FULFILLED';
export const UPDATE_CART_REJECTED = 'UPDATE_CART_REJECTED';

export const GET_CART_PRODUCT_BY_IDS = 'GET_CART_PRODUCT_BY_IDS';
export const GET_CART_PRODUCT_BY_IDS_PENDING = 'GET_CART_PRODUCT_BY_IDS_PENDING';
export const GET_CART_PRODUCT_BY_IDS_FULFILLED = 'GET_CART_PRODUCT_BY_IDS_FULFILLED';
export const GET_CART_PRODUCT_BY_IDS_REJECTED = 'GET_CART_PRODUCT_BY_IDS_REJECTED';

export const GET_CART_BY_SESSION = 'GET_CART_BY_SESSION';
export const GET_CART_BY_SESSION_PENDING = 'GET_CART_BY_SESSION_PENDING';
export const GET_CART_BY_SESSION_FULFILLED = 'GET_CART_BY_SESSION_FULFILLED';
export const GET_CART_BY_SESSION_REJECTED = 'GET_CART_BY_SESSION_REJECTED';