export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_PENDING = 'GET_ORDER_PENDING';
export const GET_ORDER_FULFILLED = 'GET_ORDER_FULFILLED';
export const GET_ORDER_REJECTED = 'GET_ORDER_REJECTED';

export const SAVE_ORDER = "SAVE_ORDER";
export const SAVE_ORDER_PENDING = "SAVE_ORDER_PENDING";
export const SAVE_ORDER_FULFILLED = "SAVE_ORDER_FULFILLED";
export const SAVE_ORDER_REJECTED = "SAVE_ORDER_REJECTED";

export const SAVE_SHIPPING = "SAVE_SHIPPING";
export const SAVE_SHIPPING_PENDING = "SAVE_SHIPPING_PENDING";
export const SAVE_SHIPPING_FULFILLED = "SAVE_SHIPPING_FULFILLED";
export const SAVE_SHIPPING_REJECTED = "SAVE_SHIPPING_REJECTED";

export const SAVE_TRACKING = "SAVE_TRACKING";
export const SAVE_TRACKING_PENDING = "SAVE_TRACKING_PENDING";
export const SAVE_TRACKING_FULFILLED = "SAVE_TRACKING_FULFILLED";
export const SAVE_TRACKING_REJECTED = "SAVE_TRACKING_REJECTED";

export const SAVE_PAYMENT = "SAVE_PAYMENT";
export const SAVE_PAYMENT_PENDING = "SAVE_PAYMENT_PENDING";
export const SAVE_PAYMENT_FULFILLED = "SAVE_PAYMENT_FULFILLED";
export const SAVE_PAYMENT_REJECTED = "SAVE_PAYMENT_REJECTED",;

export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const SAVE_PRODUCT_PENDING = "SAVE_PRODUCT_PENDING";
export const SAVE_PRODUCT_FULFILLED = "SAVE_PRODUCT_FULFILLED";
export const SAVE_PRODUCT_REJECTED = "SAVE_PRODUCT_REJECTED";