export const GET_CATEGORIES = 'GET_CATEGORIES'; 
export const GET_CATEGORIES_PENDING = 'GET_CATEGORIES_PENDING'; 
export const GET_CATEGORIES_FULFILLED = 'GET_CATEGORIES_FULFILLED'; 
export const GET_CATEGORIES_REJECTED = 'GET_CATEGORIES_REJECTED';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID'; 
export const GET_CATEGORY_BY_ID_PENDING = 'GET_CATEGORY_BY_ID_PENDING'; 
export const GET_CATEGORY_BY_ID_FULFILLED = 'GET_CATEGORY_BY_ID_FULFILLED'; 
export const GET_CATEGORY_BY_ID_REJECTED = 'GET_CATEGORY_BY_ID_REJECTED';

export const GET_PRODUCTS_BY_CATEGORY_ID = 'GET_PRODUCTS_BY_CATEGORY_ID'; 
export const GET_PRODUCTS_BY_CATEGORY_ID_PENDING = 'GET_PRODUCTS_BY_CATEGORY_ID_PENDING'; 
export const GET_PRODUCTS_BY_CATEGORY_ID_FULFILLED = 'GET_PRODUCTS_BY_CATEGORY_ID_FULFILLED'; 
export const GET_PRODUCTS_BY_CATEGORY_ID_REJECTED = 'GET_PRODUCTS_BY_CATEGORY_ID_REJECTED';